stages:
  - build
  - push

build:
  stage: build
  script:
    - /usr/bin/docker build -t registry.faked.org/gitlab-ci/android:latest .

push:
  stage: push
  script:
    - /usr/bin/docker push registry.faked.org/gitlab-ci/android:latest
